// swift-tools-version:5.5

import PackageDescription
import Foundation

let projectPath = URL(fileURLWithPath: #file).deletingLastPathComponent().path

var sources = [
  "audio/aframe.c",
  "audio/chmap.c",
  "audio/chmap_avchannel.c",
  "audio/chmap_sel.c",
  "audio/decode/ad_lavc.c",
  "audio/decode/ad_spdif.c",
  "audio/filter/af_drop.c",
  "audio/filter/af_format.c",
  "audio/filter/af_lavcac3enc.c",
  "audio/filter/af_scaletempo.c",
  "audio/filter/af_scaletempo2.c",
  "audio/filter/af_scaletempo2_internals.c",
  "audio/fmt-conversion.c",
  "audio/format.c",
  "audio/out/ao.c",
  "audio/out/ao_lavc.c",
  "audio/out/ao_null.c",
  "audio/out/ao_pcm.c",
  "audio/out/buffer.c",
  "common/av_common.c",
  "common/av_log.c",
  "common/codecs.c",
  "common/common.c",
  "common/encode_lavc.c",
  "common/msg.c",
  "common/playlist.c",
  "common/recorder.c",
  "common/stats.c",
  "common/tags.c",
  "common/version.c",
  "demux/codec_tags.c",
  "demux/cue.c",
  "demux/cache.c",
  "demux/demux.c",
  "demux/demux_cue.c",
  "demux/demux_disc.c",
  "demux/demux_edl.c",
  "demux/demux_lavf.c",
  "demux/demux_mf.c",
  "demux/demux_mkv.c",
  "demux/demux_mkv_timeline.c",
  "demux/demux_null.c",
  "demux/demux_playlist.c",
  "demux/demux_raw.c",
  "demux/demux_timeline.c",
  "demux/ebml.c",
  "demux/packet.c",
  "demux/timeline.c",
  "filters/f_async_queue.c",
  "filters/f_autoconvert.c",
  "filters/f_auto_filters.c",
  "filters/f_decoder_wrapper.c",
  "filters/f_demux_in.c",
  "filters/f_hwtransfer.c",
  "filters/f_lavfi.c",
  "filters/f_output_chain.c",
  "filters/f_swresample.c",
  "filters/f_swscale.c",
  "filters/f_utils.c",
  "filters/filter.c",
  "filters/frame.c",
  "filters/user_filters.c",
  "input/cmd.c",
  "input/event.c",
  "input/input.c",
  "input/ipc.c",
  "input/keycodes.c",
  "misc/bstr.c",
  "misc/charset_conv.c",
  "misc/codepoint_width.c",
  "misc/dispatch.c",
  "misc/io_utils.c",
  "misc/json.c",
  "misc/language.c",
  "misc/natural_sort.c",
  "misc/node.c",
  "misc/path_utils.c",
  "misc/random.c",
  "misc/rendezvous.c",
  "misc/thread_pool.c",
  "misc/thread_tools.c",
  "options/m_config_core.c",
  "options/m_config_frontend.c",
  "options/m_option.c",
  "options/m_property.c",
  "options/options.c",
  "options/parse_commandline.c",
  "options/parse_configfile.c",
  "options/path.c",
  "player/audio.c",
  "player/client.c",
  "player/command.c",
  "player/configfiles.c",
  "player/external_files.c",
  "player/loadfile.c",
  "player/main.c",
  "player/misc.c",
  "player/osd.c",
  "player/playloop.c",
  "player/screenshot.c",
  "player/scripting.c",
  "player/sub.c",
  "player/video.c",
  "stream/cookies.c",
  "stream/stream.c",
  "stream/stream_avdevice.c",
  "stream/stream_cb.c",
  "stream/stream_concat.c",
  "stream/stream_edl.c",
  "stream/stream_file.c",
  "stream/stream_lavf.c",
  "stream/stream_memory.c",
  "stream/stream_mf.c",
  "stream/stream_null.c",
  "stream/stream_slice.c",
  "sub/ass_mp.c",
  "sub/dec_sub.c",
  "sub/draw_bmp.c",
  "sub/filter_sdh.c",
  "sub/img_convert.c",
  "sub/lavc_conv.c",
  "sub/osd.c",
  "sub/osd_libass.c",
  "sub/sd_ass.c",
  "sub/sd_lavc.c",
  "video/csputils.c",
  "video/decode/vd_lavc.c",
  "video/filter/refqueue.c",
  "video/filter/vf_format.c",
  "video/filter/vf_sub.c",
  "video/fmt-conversion.c",
  "video/hwdec.c",
  "video/image_loader.c",
  "video/image_writer.c",
  "video/img_format.c",
  "video/mp_image.c",
  "video/mp_image_pool.c",
  "video/out/aspect.c",
  "video/out/bitmap_packer.c",
  "video/out/dither.c",
  "video/out/dr_helper.c",
  "video/out/filter_kernels.c",
  "video/out/gpu/context.c",
  "video/out/gpu/error_diffusion.c",
  "video/out/gpu/hwdec.c",
  "video/out/gpu/lcms.c",
  "video/out/gpu/libmpv_gpu.c",
  "video/out/gpu/osd.c",
  "video/out/gpu/ra.c",
  "video/out/gpu/shader_cache.c",
  "video/out/gpu/spirv.c",
  "video/out/gpu/user_shaders.c",
  "video/out/gpu/utils.c",
  "video/out/gpu/video.c",
  "video/out/gpu/video_shaders.c",
  "video/out/libmpv_sw.c",
  "video/out/vo.c",
  "video/out/vo_gpu.c",
  "video/out/vo_image.c",
  "video/out/vo_lavc.c",
  "video/out/vo_libmpv.c",
  "video/out/vo_null.c",
  "video/out/vo_tct.c",
  "video/out/vo_kitty.c",
  "video/out/win_state.c",
  "video/repack.c",
  "video/sws_utils.c",
  "video/out/placebo/ra_pl.c",
  "video/out/placebo/utils.c",
  "video/out/vo_gpu_next.c",
  "video/out/gpu_next/context.c",
  "osdep/io.c",
  "osdep/semaphore-mac.c",
  "osdep/subprocess.c",
  "osdep/timer.c",
  "ta/ta.c",
  "ta/ta_talloc.c",
  "ta/ta_utils.c",
  "osdep/threads-posix.c",
  "osdep/language-mac.c",
  "osdep/path-mac.m",
  "osdep/utils-mac.c",
  "osdep/mac/app_bridge.m",
  "osdep/subprocess-posix.c",
  "input/ipc-unix.c",
  "osdep/poll_wrapper.c",
  "osdep/terminal-unix.c",
  "sub/filter_regex.c",
  "osdep/path-darwin.c",
  "osdep/timer-darwin.c",
  "stream/stream_bluray.c",
  "audio/filter/af_rubberband.c",
  "video/filter/vf_fingerprint.c",
  "video/zimg.c",
  "audio/out/ao_avfoundation.m",
  "audio/out/ao_coreaudio.c",
  "audio/out/ao_coreaudio_exclusive.c",
  "audio/out/ao_coreaudio_properties.c",
  "audio/out/ao_coreaudio_chmap.c",
  "audio/out/ao_coreaudio_utils.c",
  "video/out/opengl/common.c",
  "video/out/opengl/context.c",
  "video/out/opengl/formats.c",
  "video/out/opengl/libmpv_gl.c",
  "video/out/opengl/ra_gl.c",
  "video/out/opengl/utils.c",
  "video/out/hwdec/hwdec_vulkan.c",
  "video/out/vulkan/context.c",
  "video/out/vulkan/utils.c",
  "video/filter/vf_gpu_vulkan.c",
  "video/out/vulkan/context_display.c",
  "video/filter/vf_gpu.c",
  "video/out/hwdec/hwdec_vt.c",
  "video/out/hwdec/hwdec_mac_gl.c",
  "video/out/hwdec/hwdec_vt_pl.m",
  "video/out/vulkan/context_mac.m",
  
//   main
  "osdep/main-fn-mac.c"
]

var resources: [Resource] = [
    .copy("etc/mpv.svg")
]
var linkerSettings: [LinkerSetting] = [
  .linkedLibrary("ass"),
  .linkedLibrary("unibreak"),
  .linkedLibrary("harfbuzz"),
  .linkedLibrary("glib-2.0"),
  .linkedLibrary("iconv"),
  .linkedLibrary("fribidi"),
  .linkedLibrary("freetype"),
  .linkedLibrary("png16"),
  .linkedLibrary("avutil"),
  .linkedLibrary("avformat"),
  .linkedLibrary("avcodec"),
  .linkedLibrary("avdevice"),
  .linkedLibrary("avfilter"),
  .linkedLibrary("postproc"),
  .linkedLibrary("swscale"),
  .linkedLibrary("swresample"),
  .linkedLibrary("placebo"),
  .linkedLibrary("shaderc"),
  .linkedLibrary("vulkan"),
  .linkedLibrary("lcms2"),
  .linkedLibrary("bluray"),
  .linkedLibrary("fontconfig"),
  .linkedLibrary("luajit"),
  .linkedLibrary("rubberband"),
  .linkedLibrary("samplerate"),
  .linkedLibrary("zimg"),
  .linkedLibrary("jpeg"),
  .linkedLibrary("z"),
  .linkedLibrary("turbojpeg"),
  .linkedFramework("AVFoundation"),
  .linkedFramework("AudioUnit"),
  .linkedFramework("CoreAudio"),
  .linkedFramework("OpenGL"),
  .linkedFramework("AudioToolbox"),
  .linkedFramework("CoreVideo"),
  .linkedFramework("Cocoa"),
  .linkedFramework("IOKit"),
  .linkedFramework("QuartzCore"),
  .linkedFramework("CoreMedia"),
  .linkedFramework("CoreFoundation"),
  .unsafeFlags([
    "-Lbuild/deps/libass/0.17.3/lib",
    "-Lbuild/deps/libunibreak/6.1/lib",
    "-Lbuild/deps/harfbuzz/10.0.1_1/lib",
    "-Lbuild/deps/glib/2.82.1/lib",
    "-Lbuild/deps/gettext/lib",
    "-Lbuild/deps/pcre2/10.44/lib",
    "-Lbuild/deps/fribidi/1.0.16/lib",
    "-Lbuild/deps/freetype/lib",
    "-Lbuild/deps/libpng/lib",
    "-Lbuild/deps/ffmpeg/7.1/lib",
    "-Lbuild/deps/libplacebo/7.349.0/lib",
    "-Lbuild/deps/shaderc/2024.3/lib",
    "-Lbuild/deps/vulkan-loader/1.3.296/lib",
    "-Lbuild/deps/little-cms2/2.16/lib",
    "-Lbuild/deps/libbluray/1.3.4/lib",
    "-Lbuild/deps/fontconfig/2.15.0/lib",
    "-Lbuild/deps/luajit/2.1.1727870382/lib",
    "-Lbuild/deps/rubberband/3.3.0/lib",
    "-Lbuild/deps/libsamplerate/0.2.2/lib",
    "-Lbuild/deps/zimg/3.0.5/lib",
    "-Lbuild/deps/jpeg-turbo/3.0.4/lib",
    // "-Xlinker", "build/osdep/mac/swift.o"
  ]),
]
var cSettings: [CSetting] = [
  .headerSearchPath("libmpv.2.dylib.p"),
  .headerSearchPath("."),
  .headerSearchPath("common"),
  .headerSearchPath("etc"),
  .headerSearchPath("player/javascript"),
  .headerSearchPath("player/lua"),
  .headerSearchPath("sub"),
  .headerSearchPath("TOOLS/osxbundle"),
  .headerSearchPath("osdep/mac"),
  .headerSearchPath("build/deps/libass/0.17.3/include"),
  .headerSearchPath("build/deps/libunibreak/6.1/include"),
  .headerSearchPath("build/deps/harfbuzz/10.0.1_1/include/harfbuzz"),
  .headerSearchPath("build/deps/glib/2.82.1/include/glib-2.0"),
  .headerSearchPath("build/deps/glib/2.82.1/lib/glib-2.0/include"),
  .headerSearchPath("build/deps/gettext/include"),
  .headerSearchPath("build/deps/pcre2/10.44/include"),
  .headerSearchPath("build/deps/graphite2/1.3.14/include"),
  .headerSearchPath("build/deps/fribidi/1.0.16/include/fribidi"),
  .headerSearchPath("build/deps/freetype/include/freetype2"),
  .headerSearchPath("build/deps/libpng/include/libpng16"),
  .headerSearchPath("build/deps/ffmpeg/7.1/include"),
  .headerSearchPath("build/deps/libplacebo/7.349.0/include"),
  .headerSearchPath("build/deps/shaderc/2024.3/include"),
  .headerSearchPath("build/deps/vulkan-headers/1.3.296/include"),
  .headerSearchPath("build/deps/little-cms2/2.16/include"),
  .headerSearchPath("build/deps/libbluray/1.3.4/include"),
  .headerSearchPath("build/deps/fontconfig/2.15.0/include"),
  .headerSearchPath("build/deps/luajit/2.1.1727870382/include/luajit-2.1"),
  .headerSearchPath("build/deps/rubberband/3.3.0/include"),
  .headerSearchPath("build/deps/libsamplerate/0.2.2/include"),
  .headerSearchPath("build/deps/zimg/3.0.5/include"),
  .headerSearchPath("build/deps/jpeg-turbo/3.0.4/include"),
  .headerSearchPath("build"),
  .headerSearchPath("build/common"),
  .define("D_FILE_OFFSET_BITS", to: "64"),
  .define("D_GNU_SOURCE"),
  .unsafeFlags([
    "-fvisibility=hidden",
    "-fdiagnostics-color=always",
    "-Wall",
    "-Winvalid-pch",
    "-Wextra",
    "-Werror",
    "-std=c11",
    "-O2",
    "-g",
    "-Wdisabled-optimization",
    "-Wempty-body",
    "-Wformat",
    "-Wimplicit-fallthrough",
    "-Wparentheses",
    "-Wpointer-arith",
    "-Wshadow",
    "-Wundef",
    "-Wvla",
    "-Wno-cast-function-type",
    "-Wno-format-zero-length",
    "-Wno-missing-field-initializers",
    "-Wno-sign-compare",
    "-Wno-switch",
    "-Wno-unused-parameter",
    "-fno-math-errno",
    "-fno-signed-zeros",
    "-fno-trapping-math",
    "-Werror=format-security",
    "-Wmissing-prototypes",
    "-Wstrict-prototypes",
    "-Werror=implicit-function-declaration",
    "-Wno-pointer-sign",
    "-Wno-error=deprecated",
    "-Wno-error=deprecated-declarations",
    "-Wno-conversion",
    "-Wno-strict-prototypes",
    "-fno-objc-arc",
  ]),
]

var swiftSources = [
  "osdep/mac/application.swift",
  "osdep/mac/app_hub.swift",
  "osdep/mac/event_helper.swift",
  "osdep/mac/input_helper.swift",
  "osdep/mac/libmpv_helper.swift",
  "osdep/mac/log_helper.swift",
  "osdep/mac/menu_bar.swift",
  "osdep/mac/option_helper.swift",
  "osdep/mac/precise_timer.swift",
  "osdep/mac/presentation.swift",
  "osdep/mac/swift_compat.swift",
  "osdep/mac/swift_extensions.swift",
  "osdep/mac/type_helper.swift",
  "video/out/mac/common.swift",
  "video/out/mac/title_bar.swift",
  "video/out/mac/view.swift",
  "video/out/mac/window.swift",
  "video/out/cocoa_cb_common.swift",
  "video/out/mac/gl_layer.swift",
  "video/out/mac_common.swift",
  "video/out/mac/metal_layer.swift",
  "osdep/mac/remote_command_center.swift",
  "osdep/mac/touch_bar.swift",
]

var swiftSettings: [SwiftSetting] = [
  .define("HAVE_MACOS_10_15_4_FEATURES"),
  .define("HAVE_MACOS_11_FEATURES"),
  .define("HAVE_MACOS_12_FEATURES"),
  .define("HAVE_MACOS_COCOA_CB"),
  .define("HAVE_MACOS_TOUCHBAR"),
  .define("HAVE_MACOS_MEDIA_PLAYER"),
  .unsafeFlags([
    // "-enable-objc-interop",
    "-emit-objc-header",
    "-parse-as-library",
    "-swift-version", "5",
    "-g",
    "-O",
    "-module-name", "swift",
    "-emit-module-path", "\(projectPath)/osdep/mac/swift.swiftmodule",
    "-import-objc-header", "\(projectPath)/osdep/mac/app_bridge_objc.h",
    "-emit-objc-header-path", "\(projectPath)/osdep/mac/swift.h",
    "-I", "\(projectPath)",
    "-I", "\(projectPath)/build",
    "-I", "\(projectPath)/build/deps/libplacebo/7.349.0/include",
    "-I", "\(projectPath)/build/deps/ffmpeg/7.1/include",
  ]),
]

let package = Package(
  name: "libmpv",
  platforms: [
    .macOS(.v12),
//    .iOS(.v14),
//    .tvOS(.v14),
  ],
  products: [
//    .library(name: "mpv", type: .dynamic, targets: ["mpv"])
    .executable(name: "mpv", targets: ["mpv"])
  ],
  dependencies: [],
  targets: [
    .target(
      name: "SwiftCode",
      dependencies: [],
      path: ".",
      sources: swiftSources,
      swiftSettings: swiftSettings
    ),
    .target(
      name: "mpv",
      dependencies: [
        "SwiftCode"
      ],
      path: ".",
      exclude: [
        "test",
        "TOOLS",
        "DOCS",
      ],
      sources: sources,
      resources: resources,
      publicHeadersPath: "libmpv",
      cSettings: cSettings,
      linkerSettings: linkerSettings
    ),
  ],
  cxxLanguageStandard: .cxx11
)

// ln -s /opt/homebrew/Cellar/libass build/deps
// ln -s /opt/homebrew/Cellar/libunibreak build/deps
// ln -s /opt/homebrew/Cellar/harfbuzz build/deps
// ln -s /opt/homebrew/Cellar/glib build/deps
// ln -s /opt/homebrew/opt/gettext build/deps
// ln -s /opt/homebrew/Cellar/pcre2 build/deps
// ln -s /opt/homebrew/Cellar/graphite2 build/deps
// ln -s /opt/homebrew/Cellar/fribidi build/deps
// ln -s /opt/homebrew/opt/freetype build/deps
// ln -s /opt/homebrew/opt/libpng build/deps
// ln -s /opt/homebrew/Cellar/ffmpeg build/deps
// ln -s /opt/homebrew/Cellar/libplacebo build/deps
// ln -s /opt/homebrew/Cellar/shaderc build/deps
// ln -s /opt/homebrew/Cellar/vulkan-loader build/deps
// ln -s /opt/homebrew/Cellar/vulkan-headers build/deps
// ln -s /opt/homebrew/Cellar/little-cms2 build/deps
// ln -s /opt/homebrew/Cellar/libbluray build/deps
// ln -s /opt/homebrew/Cellar/fontconfig build/deps
// ln -s /opt/homebrew/Cellar/luajit build/deps
// ln -s /opt/homebrew/Cellar/rubberband build/deps
// ln -s /opt/homebrew/Cellar/libsamplerate build/deps
// ln -s /opt/homebrew/Cellar/zimg build/deps
// ln -s /opt/homebrew/Cellar/jpeg-turbo build/deps
